### ISSUE TITLE
This is probobly a bug you should probobly have setError with different error message here

### ISSUE THREAD

**Issue by BekaBadzagua** [Leonssizm/questionary-project#27]
https://github.com/Leonssizm/questionary-project/blob/a7cb27614546594d920749a3be6def5f3e248cfc/assets/scripts/coordinates.js#L67

**Comment by Leonssizm** [comment]
this is not a bug, in documentation, the requirement was that phone number should not have been mandatory, therefore if the field was empty, it should have been valid. on the other hand, if input was filled, number should have been in correct format.

**Comment by BekaBadzagua** [comment]
Then you dont need another else block in the end
